
package pulleys;

/**
 * A Trigger can fire a Transition in a StateMachine. Whether it actually fires
 * a Transition or not depends on a number of factors. Triggers are generated by
 * Stateful objects or objects referencing Stateful objects.
 *
 * <p>When {@link Stateful#pullTrigger(Trigger, Object)} is called, the trigger
 * is first {@link #eval(Stateful, Object)}uated. Then, it's mapped to a set of
 * valid transitions based off its Class and its parameters. Finally, any
 * Transitions that have active exit States fire in the order they were set up
 * in a Trigger-Map.</p>
 *
 * @author Orr Bernstein
 */
public interface Trigger {
    /**
     * Evaluates a trigger. If this method returns true, the trigger may fire
     * one of more Transitions
     *
     * @param stateful the Stateful we pulled this Trigger on.
     * @param param a parameter used to look up valid Transitions for this
     *              trigger. Usually a String, may be set null, and may be set
     *              to the wildcard '*' to fire all transitions mapped to this
     *              Class of trigger.
     * @param cond A Condition structure to be evaluated, which can be null.
     *
     * @return True, if this trigger should continue executing
     */
    boolean eval(Stateful stateful, Object param, Condition cond);
}
